import Applications from "./applications";
import { Application, columns } from "./columns";
import { DataTable } from "./data-table";
import { getApplications } from "./get-applications";

// export const applications: Application[] = [
//   {
//     id: "app-1",
//     resume: { id: "res-1", name: "Resume A" },
//     role: "Software Engineer",
//     company: "Google",
//     location: "Mountain View, CA",
//     jobDescription: "Frontend web development with React and TypeScript.",
//     applicationUrl: "https://careers.google.com/jobs/apply/123",
//     dateAdded: new Date("2025-01-10T09:00:00Z"),
//     dateApplied: new Date("2025-01-11T10:00:00Z"),
//     dateResponded: new Date("2025-01-17T12:00:00Z"),
//     dateInterviewed: new Date("2025-01-20T15:00:00Z"),
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-2",
//     resume: { id: "res-2", name: "Resume B" },
//     role: "Backend Developer",
//     company: "Amazon",
//     location: "Seattle, WA",
//     jobDescription:
//       "Work on distributed systems powering AWS and improve scalability.",
//     applicationUrl: "https://amazon.jobs/apply/456",
//     dateAdded: new Date("2025-01-15T14:00:00Z"),
//     dateApplied: new Date("2025-01-16T16:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-3",
//     resume: { id: "res-3", name: "Resume C" },
//     role: "Data Scientist",
//     company: "Meta",
//     location: "Menlo Park, CA",
//     jobDescription: "Build ML models for personalized recommendations.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-02-01T12:00:00Z"),
//     dateApplied: new Date("2025-02-02T13:00:00Z"),
//     dateResponded: new Date("2025-02-05T09:00:00Z"),
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-4",
//     resume: null,
//     role: "DevOps Engineer",
//     company: "Netflix",
//     location: "Los Gatos, CA",
//     jobDescription: "Manage CI/CD pipelines and cloud infrastructure.",
//     applicationUrl: "https://jobs.netflix.com/openings/789",
//     dateAdded: new Date("2025-02-03T10:30:00Z"),
//     dateApplied: new Date("2025-02-04T11:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-5",
//     resume: { id: "res-4", name: "Resume D" },
//     role: "Full Stack Developer",
//     company: "Stripe",
//     location: "San Francisco, CA",
//     jobDescription: "Develop scalable APIs and improve payment systems.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-02-05T09:00:00Z"),
//     dateApplied: new Date("2025-02-05T11:00:00Z"),
//     dateResponded: new Date("2025-02-07T14:00:00Z"),
//     dateInterviewed: new Date("2025-02-10T16:00:00Z"),
//     dateAccepted: new Date("2025-02-15T12:00:00Z"),
//     dateClosed: null,
//   },
//   {
//     id: "app-6",
//     resume: { id: "res-5", name: "Resume E" },
//     role: "Product Manager",
//     company: "Apple",
//     location: "Cupertino, CA",
//     jobDescription: "Drive product strategy and roadmap for iOS team.",
//     applicationUrl: "https://jobs.apple.com/job/pm-123",
//     dateAdded: new Date("2025-02-07T13:30:00Z"),
//     dateApplied: new Date("2025-02-08T09:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-7",
//     resume: null,
//     role: "UI/UX Designer",
//     company: "Airbnb",
//     location: "San Francisco, CA",
//     jobDescription: "Design user experiences for mobile booking apps.",
//     applicationUrl: "https://airbnb.design/careers",
//     dateAdded: new Date("2025-02-09T15:00:00Z"),
//     dateApplied: null,
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-8",
//     resume: { id: "res-6", name: "Resume F" },
//     role: "Cloud Engineer",
//     company: "Microsoft",
//     location: "Redmond, WA",
//     jobDescription: "Scale and optimize Azure services.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-02-11T11:00:00Z"),
//     dateApplied: new Date("2025-02-11T12:00:00Z"),
//     dateResponded: new Date("2025-02-13T10:00:00Z"),
//     dateInterviewed: new Date("2025-02-17T14:30:00Z"),
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-9",
//     resume: { id: "res-7", name: "Resume G" },
//     role: "Security Engineer",
//     company: "Cloudflare",
//     location: "Remote",
//     jobDescription: "Secure internal and customer-facing infrastructure.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-02-14T08:30:00Z"),
//     dateApplied: new Date("2025-02-15T09:15:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: new Date("2025-02-28T10:00:00Z"),
//   },
//   {
//     id: "app-10",
//     resume: null,
//     role: "QA Engineer",
//     company: "Slack",
//     location: "San Francisco, CA",
//     jobDescription: "Test messaging features and internal tooling.",
//     applicationUrl: "https://slack.com/careers",
//     dateAdded: new Date("2025-02-20T12:00:00Z"),
//     dateApplied: null,
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-11",
//     resume: { id: "res-8", name: "Resume H" },
//     role: "Machine Learning Engineer",
//     company: "OpenAI",
//     location: "San Francisco, CA",
//     jobDescription: "Deploy state-of-the-art LLM applications.",
//     applicationUrl: "https://jobs.openai.com/mleng",
//     dateAdded: new Date("2025-02-21T13:20:00Z"),
//     dateApplied: new Date("2025-02-21T14:00:00Z"),
//     dateResponded: new Date("2025-02-23T16:00:00Z"),
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-12",
//     resume: null,
//     role: "Mobile Developer",
//     company: "Spotify",
//     location: "Stockholm, Sweden",
//     jobDescription: "Build music streaming experiences in iOS and Android.",
//     applicationUrl: "https://spotifyjobs.com/mobile",
//     dateAdded: new Date("2025-02-24T18:00:00Z"),
//     dateApplied: new Date("2025-02-25T08:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-13",
//     resume: { id: "res-9", name: "Resume I" },
//     role: "SDET",
//     company: "Atlassian",
//     location: "Sydney, Australia",
//     jobDescription: "Automate test coverage for Jira platform.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-02-25T09:00:00Z"),
//     dateApplied: null,
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-14",
//     resume: { id: "res-10", name: "Resume J" },
//     role: "Systems Engineer",
//     company: "Tesla",
//     location: "Palo Alto, CA",
//     jobDescription: "Optimize embedded systems in automotive software.",
//     applicationUrl: "https://tesla.com/careers",
//     dateAdded: new Date("2025-02-28T15:00:00Z"),
//     dateApplied: new Date("2025-03-01T09:00:00Z"),
//     dateResponded: new Date("2025-03-02T12:00:00Z"),
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-15",
//     resume: null,
//     role: "Frontend Engineer",
//     company: "Twitter (X)",
//     location: "San Francisco, CA",
//     jobDescription: "Develop timeline rendering performance optimizations.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-03-02T08:00:00Z"),
//     dateApplied: new Date("2025-03-02T14:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-16",
//     resume: { id: "res-11", name: "Resume K" },
//     role: "AI Research Assistant",
//     company: "DeepMind",
//     location: "London, UK",
//     jobDescription: "Assist with reinforcement learning research codebases.",
//     applicationUrl: "https://deepmind.com/careers/research-assistant",
//     dateAdded: new Date("2025-03-03T11:00:00Z"),
//     dateApplied: new Date("2025-03-03T15:00:00Z"),
//     dateResponded: new Date("2025-03-05T10:00:00Z"),
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-17",
//     resume: null,
//     role: "Blockchain Developer",
//     company: "Coinbase",
//     location: "Remote",
//     jobDescription: "Build blockchain integrations and custody services.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-03-04T09:00:00Z"),
//     dateApplied: null,
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-18",
//     resume: { id: "res-12", name: "Resume L" },
//     role: "Site Reliability Engineer",
//     company: "GitHub",
//     location: "Remote",
//     jobDescription: "Ensure uptime and reliability of GitHub services.",
//     applicationUrl: "https://github.com/careers",
//     dateAdded: new Date("2025-03-07T10:30:00Z"),
//     dateApplied: new Date("2025-03-08T09:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: new Date("2025-03-12T11:00:00Z"),
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-19",
//     resume: { id: "res-13", name: "Resume M" },
//     role: "Game Developer",
//     company: "Epic Games",
//     location: "Cary, NC",
//     jobDescription: "Develop engine features for Unreal Engine 6.",
//     applicationUrl: null,
//     dateAdded: new Date("2025-03-09T15:00:00Z"),
//     dateApplied: new Date("2025-03-10T09:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
//   {
//     id: "app-20",
//     resume: { id: "res-14", name: "Resume N" },
//     role: "Robotics Engineer",
//     company: "Boston Dynamics",
//     location: "Waltham, MA",
//     jobDescription: "Build navigation and control systems for robotics.",
//     applicationUrl: "https://bostondynamics.com/careers",
//     dateAdded: new Date("2025-03-12T09:00:00Z"),
//     dateApplied: new Date("2025-03-13T10:00:00Z"),
//     dateResponded: null,
//     dateInterviewed: null,
//     dateAccepted: null,
//     dateClosed: null,
//   },
// ];

export default async function Page() {
  const [applications] = await Promise.all([getApplications()])

  return (
    <div className="container mx-auto pb-10">
      <DataTable columns={columns} initData={applications} />
    </div>
  )
}