export type LandingPageApplication = {
  id: string
  jobTitle: string
  company: string
  location: string
  dateAdded: Date
  dateApplied: Date | null
  dateResponded: Date | null
  dateInterviewed: Date | null
  dateAccepted: Date | null
  dateClosed: Date | null
}

export const mockData: LandingPageApplication[] = [
  {
    id: "1",
    jobTitle: "Frontend Developer",
    company: "TechNova",
    location: "San Francisco, CA",
    dateAdded: new Date("2025-01-01"),
    dateApplied: new Date("2025-01-10"),
    dateResponded: new Date("2025-01-15"),
    dateInterviewed: new Date("2025-01-20"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "2",
    jobTitle: "Backend Engineer",
    company: "CloudWorks",
    location: "New York, NY",
    dateAdded: new Date("2025-01-02"),
    dateApplied: new Date("2025-01-12"),
    dateResponded: new Date("2025-01-18"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "3",
    jobTitle: "Product Manager",
    company: "InnoSoft",
    location: "Austin, TX",
    dateAdded: new Date("2025-01-03"),
    dateApplied: new Date("2025-01-05"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "4",
    jobTitle: "Data Scientist",
    company: "AI Labs",
    location: "Boston, MA",
    dateAdded: new Date("2025-01-04"),
    dateApplied: new Date("2025-01-08"),
    dateResponded: new Date("2025-01-14"),
    dateInterviewed: new Date("2025-01-22"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "5",
    jobTitle: "UX Designer",
    company: "PixelPerfect",
    location: "Seattle, WA",
    dateAdded: new Date("2025-01-05"),
    dateApplied: new Date("2025-01-03"),
    dateResponded: new Date("2025-01-07"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: new Date("2025-01-15"),
  },
  {
    id: "6",
    jobTitle: "DevOps Engineer",
    company: "CloudOps",
    location: "Denver, CO",
    dateAdded: new Date("2025-01-06"),
    dateApplied: new Date("2025-01-11"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "7",
    jobTitle: "Mobile Developer",
    company: "Appify",
    location: "Chicago, IL",
    dateAdded: new Date("2025-01-07"),
    dateApplied: new Date("2025-01-09"),
    dateResponded: new Date("2025-01-13"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "8",
    jobTitle: "QA Engineer",
    company: "QualityFirst",
    location: "Portland, OR",
    dateAdded: new Date("2025-01-08"),
    dateApplied: new Date("2025-01-06"),
    dateResponded: new Date("2025-01-12"),
    dateInterviewed: new Date("2025-01-19"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "9",
    jobTitle: "Full Stack Developer",
    company: "StackFlow",
    location: "Remote",
    dateAdded: new Date("2025-01-09"),
    dateApplied: new Date("2025-01-04"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "10",
    jobTitle: "Systems Analyst",
    company: "DataCore",
    location: "Atlanta, GA",
    dateAdded: new Date("2025-01-10"),
    dateApplied: new Date("2025-01-02"),
    dateResponded: new Date("2025-01-06"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "11",
    jobTitle: "Security Engineer",
    company: "SafeNet",
    location: "Washington, DC",
    dateAdded: new Date("2025-01-11"),
    dateApplied: new Date("2025-01-14"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "12",
    jobTitle: "AI Engineer",
    company: "NeuralWorks",
    location: "San Jose, CA",
    dateAdded: new Date("2025-01-12"),
    dateApplied: new Date("2025-01-07"),
    dateResponded: new Date("2025-01-10"),
    dateInterviewed: new Date("2025-01-18"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "13",
    jobTitle: "Technical Writer",
    company: "DocuTech",
    location: "Remote",
    dateAdded: new Date("2025-01-13"),
    dateApplied: new Date("2025-01-01"),
    dateResponded: new Date("2025-01-05"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: new Date("2025-01-09"),
  },
  {
    id: "14",
    jobTitle: "Solutions Architect",
    company: "CloudBridge",
    location: "Dallas, TX",
    dateAdded: new Date("2025-01-14"),
    dateApplied: new Date("2025-01-16"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "15",
    jobTitle: "Business Analyst",
    company: "InsightCorp",
    location: "Philadelphia, PA",
    dateAdded: new Date("2025-01-15"),
    dateApplied: new Date("2025-01-13"),
    dateResponded: new Date("2025-01-17"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "16",
    jobTitle: "Cloud Engineer",
    company: "SkyNet",
    location: "Los Angeles, CA",
    dateAdded: new Date("2025-01-16"),
    dateApplied: new Date("2025-01-09"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "17",
    jobTitle: "IT Support Specialist",
    company: "HelpDeskPro",
    location: "Phoenix, AZ",
    dateAdded: new Date("2025-01-17"),
    dateApplied: new Date("2025-01-05"),
    dateResponded: new Date("2025-01-08"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "18",
    jobTitle: "Machine Learning Engineer",
    company: "DeepVision",
    location: "Palo Alto, CA",
    dateAdded: new Date("2025-01-18"),
    dateApplied: new Date("2025-01-12"),
    dateResponded: new Date("2025-01-16"),
    dateInterviewed: new Date("2025-01-23"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "19",
    jobTitle: "Database Administrator",
    company: "DataKeep",
    location: "Houston, TX",
    dateAdded: new Date("2025-01-19"),
    dateApplied: new Date("2025-01-03"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "20",
    jobTitle: "Network Engineer",
    company: "NetLink",
    location: "Miami, FL",
    dateAdded: new Date("2025-01-20"),
    dateApplied: new Date("2025-01-11"),
    dateResponded: new Date("2025-01-15"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "21",
    jobTitle: "Software Engineer",
    company: "CodeWorks",
    location: "Remote",
    dateAdded: new Date("2025-01-21"),
    dateApplied: new Date("2025-01-06"),
    dateResponded: new Date("2025-01-09"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "22",
    jobTitle: "UI Designer",
    company: "Designify",
    location: "San Diego, CA",
    dateAdded: new Date("2025-01-22"),
    dateApplied: new Date("2025-01-04"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "23",
    jobTitle: "Cloud Security Engineer",
    company: "SecureCloud",
    location: "Seattle, WA",
    dateAdded: new Date("2025-01-23"),
    dateApplied: new Date("2025-01-15"),
    dateResponded: new Date("2025-01-19"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "24",
    jobTitle: "Data Engineer",
    company: "DataForge",
    location: "Chicago, IL",
    dateAdded: new Date("2025-01-24"),
    dateApplied: new Date("2025-01-08"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "25",
    jobTitle: "AI Researcher",
    company: "BrainTech",
    location: "Cambridge, MA",
    dateAdded: new Date("2025-01-25"),
    dateApplied: new Date("2025-01-02"),
    dateResponded: new Date("2025-01-07"),
    dateInterviewed: new Date("2025-01-14"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "26",
    jobTitle: "Technical Support Engineer",
    company: "Supportly",
    location: "Remote",
    dateAdded: new Date("2025-01-26"),
    dateApplied: new Date("2025-01-10"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "27",
    jobTitle: "Cloud Consultant",
    company: "CloudAdvisors",
    location: "New York, NY",
    dateAdded: new Date("2025-01-27"),
    dateApplied: new Date("2025-01-14"),
    dateResponded: new Date("2025-01-18"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "28",
    jobTitle: "Embedded Systems Engineer",
    company: "ChipWorks",
    location: "San Jose, CA",
    dateAdded: new Date("2025-01-28"),
    dateApplied: new Date("2025-01-09"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "29",
    jobTitle: "Game Developer",
    company: "PlayForge",
    location: "Los Angeles, CA",
    dateAdded: new Date("2025-01-29"),
    dateApplied: new Date("2025-01-07"),
    dateResponded: new Date("2025-01-11"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "30",
    jobTitle: "Blockchain Developer",
    company: "CryptoLabs",
    location: "Remote",
    dateAdded: new Date("2025-01-30"),
    dateApplied: new Date("2025-01-05"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "31",
    jobTitle: "Site Reliability Engineer",
    company: "Reliant",
    location: "Austin, TX",
    dateAdded: new Date("2025-01-31"),
    dateApplied: new Date("2025-01-12"),
    dateResponded: new Date("2025-01-16"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "32",
    jobTitle: "Cloud Infrastructure Engineer",
    company: "InfraCloud",
    location: "Denver, CO",
    dateAdded: new Date("2025-02-01"),
    dateApplied: new Date("2025-01-03"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "33",
    jobTitle: "Research Scientist",
    company: "FutureLabs",
    location: "Boston, MA",
    dateAdded: new Date("2025-02-02"),
    dateApplied: new Date("2025-01-01"),
    dateResponded: new Date("2025-01-06"),
    dateInterviewed: new Date("2025-01-12"),
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "34",
    jobTitle: "IT Project Manager",
    company: "ManageIT",
    location: "Philadelphia, PA",
    dateAdded: new Date("2025-02-03"),
    dateApplied: new Date("2025-01-13"),
    dateResponded: null,
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
  {
    id: "35",
    jobTitle: "Cybersecurity Analyst",
    company: "CyberSafe",
    location: "Remote",
    dateAdded: new Date("2025-02-04"),
    dateApplied: new Date("2025-01-11"),
    dateResponded: new Date("2025-01-15"),
    dateInterviewed: null,
    dateAccepted: null,
    dateClosed: null,
  },
]